from __future__ import annotations

from pathlib import Path

from butler_main.repo_layout import PRODUCT_CHAT_REL

CHAT_ASSETS_HOME_REL = PRODUCT_CHAT_REL / "assets"
CHAT_BOOTSTRAP_HOME_REL = CHAT_ASSETS_HOME_REL / "bootstrap"
CHAT_DIALOGUES_HOME_REL = CHAT_ASSETS_HOME_REL / "dialogues"
CHAT_ROLES_HOME_REL = CHAT_ASSETS_HOME_REL / "roles"

CHAT_AGENT_ROLE_FILE_REL = CHAT_ROLES_HOME_REL / "chat-agent.md"
CHAT_FEISHU_DIALOGUE_FILE_REL = CHAT_DIALOGUES_HOME_REL / "feishu-dialogue.md"
CHAT_WEIXIN_DIALOGUE_FILE_REL = CHAT_DIALOGUES_HOME_REL / "weixin-dialogue.md"
CHAT_CLI_DIALOGUE_FILE_REL = CHAT_DIALOGUES_HOME_REL / "cli-dialogue.md"
CHAT_BOOTSTRAP_SOUL_FILE_REL = CHAT_BOOTSTRAP_HOME_REL / "SOUL.md"
CHAT_BOOTSTRAP_CHAT_FILE_REL = CHAT_BOOTSTRAP_HOME_REL / "CHAT.md"
CHAT_BOOTSTRAP_TALK_FILE_REL = CHAT_BOOTSTRAP_HOME_REL / "TALK.md"
CHAT_BOOTSTRAP_USER_FILE_REL = CHAT_BOOTSTRAP_HOME_REL / "USER.md"
CHAT_BOOTSTRAP_TOOLS_FILE_REL = CHAT_BOOTSTRAP_HOME_REL / "TOOLS.md"
CHAT_BOOTSTRAP_MEMORY_POLICY_FILE_REL = CHAT_BOOTSTRAP_HOME_REL / "MEMORY_POLICY.md"

__all__ = [
    "CHAT_ASSETS_HOME_REL",
    "CHAT_AGENT_ROLE_FILE_REL",
    "CHAT_BOOTSTRAP_CHAT_FILE_REL",
    "CHAT_BOOTSTRAP_HOME_REL",
    "CHAT_BOOTSTRAP_MEMORY_POLICY_FILE_REL",
    "CHAT_BOOTSTRAP_SOUL_FILE_REL",
    "CHAT_BOOTSTRAP_TALK_FILE_REL",
    "CHAT_BOOTSTRAP_TOOLS_FILE_REL",
    "CHAT_BOOTSTRAP_USER_FILE_REL",
    "CHAT_CLI_DIALOGUE_FILE_REL",
    "CHAT_DIALOGUES_HOME_REL",
    "CHAT_FEISHU_DIALOGUE_FILE_REL",
    "CHAT_ROLES_HOME_REL",
    "CHAT_WEIXIN_DIALOGUE_FILE_REL",
]
