[pytest]
testpaths = butler_main/butler_bot_code/tests
python_files = test_*.py
cache_dir = .pytest_cache
addopts = --basetemp=./.pytest_tmp
filterwarnings =
    ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version\.:DeprecationWarning
