"""Formal second-layer surface for workflow, governance, and session substrate."""

from importlib import import_module
from typing import Any

from .bindings import RoleBinding
from .contracts import (
    CollaborationPrimitiveContract,
    FROZEN_TYPED_PRIMITIVE_IDS,
    FROZEN_TYPED_PRIMITIVES,
    primitive_contract_by_id,
)
from .engine import (
    AcceptanceReceipt,
    ConversationPromptBuild,
    ConversationTurnEngine,
    ConversationTurnInput,
    ConversationTurnOutput,
    ConversationTurnState,
    EDGE_KINDS,
    ExecutionReceipt,
    FileSessionCheckpointStore,
    FileWorkflowCheckpointStore,
    PROCESS_ROLES,
    ProcessExecutionOutcome,
    ProcessWritebackProjection,
    RuntimeVerdict,
    RuntimeSessionCheckpoint,
    STEP_KINDS,
    StepResult,
    SubworkflowCapability,
    WorkflowReceipt,
    merge_session_snapshots,
    normalize_edge_kind,
    normalize_failure_class,
    normalize_process_role,
    normalize_step_kind,
)
from .factory import WorkflowFactory
from .governance import (
    APPROVAL_STATUSES,
    APPROVAL_TYPES,
    ApprovalTicket,
    DecisionReceipt,
    ExperienceRecord,
    HandoffReceipt,
    RECOVERY_ACTIONS,
    RecoveryDirective,
    StepReceipt,
    VERIFICATION_DECISIONS,
    VerificationReceipt,
    check_bash_chain_permissions,
    extract_bash_commands,
    matches_bash_permission,
    normalize_approval_status,
    normalize_approval_type,
)
from .session import (
    ArtifactRecord,
    ArtifactRegistry,
    ArtifactVisibility,
    BlackboardEntry,
    CollaborationSubstrate,
    FileWorkflowEventLog,
    FileWorkflowSessionStore,
    JoinContract,
    MailboxMessage,
    RoleHandoff,
    SharedState,
    StepOwnership,
    WorkflowBlackboard,
    WorkflowSession,
    WorkflowSessionBundle,
    WorkflowSessionEvent,
)
from .templates import WorkflowTemplate
from .workflow import (
    WorkflowCheckpoint,
    WorkflowCursor,
    WorkflowEdgeSpec,
    WorkflowRunProjection,
    WorkflowSpec,
    WorkflowStepSpec,
)

__all__ = [
    "APPROVAL_STATUSES",
    "APPROVAL_TYPES",
    "AcceptanceReceipt",
    "ApprovalTicket",
    "ArtifactRecord",
    "ArtifactRegistry",
    "ArtifactVisibility",
    "BlackboardEntry",
    "CollaborationPrimitiveContract",
    "CollaborationSubstrate",
    "ConversationPromptBuild",
    "ConversationTurnEngine",
    "ConversationTurnInput",
    "ConversationTurnOutput",
    "ConversationTurnState",
    "DecisionReceipt",
    "EDGE_KINDS",
    "ExecutionReceipt",
    "ExecutionRuntime",
    "ExperienceRecord",
    "FROZEN_TYPED_PRIMITIVE_IDS",
    "FROZEN_TYPED_PRIMITIVES",
    "FileSessionCheckpointStore",
    "FileWorkflowCheckpointStore",
    "FileWorkflowEventLog",
    "FileWorkflowSessionStore",
    "HandoffReceipt",
    "JoinContract",
    "MailboxMessage",
    "PROCESS_ROLES",
    "ProcessExecutionOutcome",
    "ProcessWritebackProjection",
    "RECOVERY_ACTIONS",
    "RoleBinding",
    "RoleHandoff",
    "RuntimeVerdict",
    "RuntimeSessionCheckpoint",
    "RecoveryDirective",
    "STEP_KINDS",
    "SharedState",
    "StepOwnership",
    "StepReceipt",
    "StepResult",
    "SubworkflowCapability",
    "VERIFICATION_DECISIONS",
    "VerificationReceipt",
    "WorkflowBlackboard",
    "WorkflowCheckpoint",
    "WorkflowCursor",
    "WorkflowEdgeSpec",
    "WorkflowFactory",
    "WorkflowReceipt",
    "WorkflowRunProjection",
    "WorkflowSession",
    "WorkflowSessionBundle",
    "WorkflowSessionEvent",
    "WorkflowSpec",
    "WorkflowStepSpec",
    "WorkflowTemplate",
    "check_bash_chain_permissions",
    "extract_bash_commands",
    "matches_bash_permission",
    "merge_session_snapshots",
    "normalize_approval_status",
    "normalize_approval_type",
    "normalize_edge_kind",
    "normalize_failure_class",
    "normalize_process_role",
    "normalize_step_kind",
    "primitive_contract_by_id",
]


def __getattr__(name: str) -> Any:
    if name != "ExecutionRuntime":
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = import_module(".engine", __name__).ExecutionRuntime
    globals()[name] = value
    return value
